services:
  mongodb:
    image: mongo:5.0.6
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongodb
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$PORT
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - MASTER_CSV_URL=$MASTER_CSV_URL
      - ARTICLES_CSV_URL=$ARTICLES_CSV_URL
      - SUPERPLANTS_CSV_URL=$SUPERPLANTS_CSV_URL
      - LOCAL_MAP_CSV_URL=$LOCAL_MAP_CSV_URL
      - ONLINE_STORES_CSV_URL=$ONLINE_STORES_CSV_URL
      - IMAGE_URLS_SHEET_ID=$IMAGE_URLS_SHEET_ID
      - CONTACT_SHEET_ID=$CONTACT_SHEET_ID
      - CONTACT_FILES_FOLDER_ID=$CONTACT_FILES_FOLDER_ID
    stdin_open: true
    tty: true
    volumes:
      - /images:/app/images


volumes:
  db:
  images:
