apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "helm-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hostAliases }}
      hostAliases:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: {{ .Release.Name }}-app-images
        persistentVolumeClaim:
          claimName: {{ printf "%s-app-images" .Release.Name }}
      - name: {{ .Release.Name }}-mongo-data
        persistentVolumeClaim:
          claimName: {{ printf "%s-mongo-data" .Release.Name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        {{- with .Values.db }}
        - name: {{ $.Chart.Name }}-db
          image: "{{ .image.repository }}:{{ .image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          envFrom:
          - secretRef:
              name: pac-api
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo
                  key: username
                  optional: false
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo
                  key: password
                  optional: false
          ports:
            - name: mongo
              containerPort: 27017
              protocol: TCP
          volumeMounts:
            - name: {{ $.Release.Name }}-mongo-data
              mountPath: /data/db
              subPath: mongo-data
        {{- end }}
        {{- with .Values.app }}
        - name: {{ $.Chart.Name }}-app
          image: "{{ .image.repository }}:{{ .image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          env:
            - name: PORT
              value: '3000'
            - name: DB_HOST
              value: {{ include "helm-chart.fullname" $ }}
            - name: DB_POST
              value: '27017'
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mongo
                  key: username
                  optional: false
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo
                  key: password
                  optional: false
            - name: DB_NAME
              value: {{ $.Values.db.name }}
            - name: MASTER_CSV_URL
              valueFrom:
                secretKeyRef:
                  name: app
                  key: MASTER_CSV_URL
                  optional: false
            - name: ARTICLES_CSV_URL
              valueFrom:
                secretKeyRef:
                  name: app
                  key: ARTICLES_CSV_URL
                  optional: false
            - name: IMAGE_URLS_SHEET_ID
              valueFrom:
                secretKeyRef:
                  name: app
                  key: IMAGE_URLS_SHEET_ID
                  optional: false
            - name: PAC_API_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: pac-api
                  key: PAC_API_BASE_URL
                  optional: false
            - name: PAC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: pac-api
                  key: PAC_API_KEY
                  optional: false
            - name: SUPERPLANTS_CSV_URL
              valueFrom:
                secretKeyRef:
                  name: app
                  key: SUPERPLANTS_CSV_URL
                  optional: false
            - name: LOCAL_MAP_CSV_URL
              valueFrom:
                secretKeyRef:
                  name: app
                  key: LOCAL_MAP_CSV_URL
                  optional: false
            - name: CONTACT_SHEET_ID
              valueFrom:
                secretKeyRef:
                  name: app
                  key: CONTACT_SHEET_ID
                  optional: false
            - name: CONTACT_FILES_FOLDER_ID
              valueFrom:
                secretKeyRef:
                  name: app
                  key: CONTACT_FILES_FOLDER_ID
                  optional: false
            - name: ONLINE_STORES_CSV_URL
              valueFrom:
                secretKeyRef:
                  name: app
                  key: ONLINE_STORES_CSV_URL
                  optional: false
            - name: SERVICE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: app
                  key: SERVICE_ACCOUNT
                  optional: false
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: linode-storage
                  key: AWS_ACCESS_KEY_ID
                  optional: false
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: linode-storage
                  key: AWS_SECRET_ACCESS_KEY
                  optional: false
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: linode-storage
                  key: AWS_DEFAULT_REGION
                  optional: false
            - name: LINODE_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: linode-storage
                  key: LINODE_BUCKET_NAME
                  optional: false
            - name: LINODE_ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: linode-storage
                  key: LINODE_ENDPOINT_URL
                  optional: false
            {{- with $.Values.app.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: app-config
                optional: true
            {{- with $.Values.app.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: {{ $.Release.Name }}-app-images
              mountPath: /app/images
              subPath: app-images
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 3
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
