apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongo
  selector:
    {{- include "helm-chart.selectorLabels" . | nindent 4 }}
