#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e
cd "$(dirname "$0")/.."


script/bootstrap
script/-check-docker-compose

echo
echo "==> Downloading and restoring test data into mongodb…"
curl 'https://boutell.dev/pa-wildflower-selector/pa-wildflower-selector.archive.gz' \
     | gunzip -c \
     | docker-compose exec -T mongodb bash -c '
        mongorestore \
            --drop \
            --archive \
            --username=${MONGO_INITDB_ROOT_USERNAME} \
            --password=${MONGO_INITDB_ROOT_PASSWORD}
    '

echo
echo "==> Downloading and restoring test data into app…"
docker-compose exec app rm -r /app/images
curl 'https://boutell.dev/pa-wildflower-selector/pa-wildflower-selector.tar' \
 | docker-compose exec -T app tar -xvf -

echo
echo "==> Running massage script…"
docker-compose exec app node massage

echo
echo "==> App is now ready to go!"
echo "    * Open http://localhost:6868"
# echo "    * Login with Username: root"
# echo "                 Password: password"
# echo
