#!/bin/bash

export SEALED_SECRETS_CERT=https://sealed-secrets.live.k8s.phl.io/v1/cert.pem

kubeseal \
    --namespace "choose-native-plants" \
    -f secrets.yaml \
    -w ~/CodeForPhilly/cfp-live-cluster/choose-native-plants.secrets/app.yaml
